version: "3.9"

services:

  web:
    container_name: gneppa_cont
    build: .
    restart: always
    image: gneppa
    entrypoint: /docker-entrypoint.sh
    volumes:
      - ./backend:/backend
      - static_volume:/backend/staticfiles
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: NGNIX
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./backend:/backend
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/backend/staticfiles
      - ./certbot/www/:/var/www/certbot/:r
      - ./certbot/conf/:/etc/letsencrypt/:r
    depends_on:
      - web

  db:
    image: postgres:latest
    container_name: POSTGRES
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/posgresql/data

  certbot:
    container_name: CERTBOT
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
  static_volume:
  pgdata:
