version: "3.9"

services:

  web:
    container_name: gneppa_cont
    build: .
    restart: always
    image: gneppa
    entrypoint: /docker-entrypoint.sh
    volumes:
      - ./backend:/backend
      - static_volume:/backend/staticfiles
    depends_on:
      - db


  nginx:
    image: nginx:latest
    #image: nginx
    container_name: NGNIX
    ports:
      - 80:80
    volumes:
      - ./backend:/backend
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/backend/staticfiles
    depends_on:
      - web

  db:
    image: postgres:latest
    #image: postgres:16.0-alpine3.17
    container_name: POSTGRES
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/posgresql/data

volumes:
  static_volume:
  pgdata:
