# Generated by Django 4.2.3 on 2023-11-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
