# Generated by Django 3.2 on 2022-09-12 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocablevel',
            name='example',
        ),
    ]
