# Generated by Django 3.2 on 2022-09-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_vocablevel_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocablevel',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
