# Generated by Django 3.2 on 2022-07-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appfile',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
