# Generated by Django 3.2 on 2022-07-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_appfile_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppFile',
        ),
    ]
