# Generated by Django 3.2 on 2022-09-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_vocablevel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocablevel',
            name='example',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vocablevel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
