# Generated by Django 3.2 on 2022-09-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220912_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(blank=True, max_length=250, null=True)),
                ('counter', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
