# Generated by Django 3.2 on 2022-07-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='appfile',
            name='platform',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appfile',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
