# Generated by Django 3.2 on 2022-07-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220719_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appfile',
            old_name='counter',
            new_name='count',
        ),
    ]
