# Generated by Django 4.2 on 2023-05-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_clickcounter'),
        ('app', '0007_rename_counter_appfile_count'),
    ]

    operations = [
    ]
