# Generated by Django 4.2 on 2023-05-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20230513_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
