# Generated by Django 4.2 on 2023-05-13 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_level_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='icon',
            field=models.CharField(blank=True, default='circle', max_length=100, null=True),
        ),
    ]
